***
# Concatenating and merging data

Combine several `Series` or `DataFrame` objects:

1. [`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html):
   combine multiple Series/DataFrames by appending observations (rows) or columns.
2. [`pd.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html):
   match observations from two DataFrames or named Series and combine these into a
   _merged_ DataFrame.

***
## Concatenation

### Concatenating Series

In [172]:
# Create demo series
import pandas as pd

a = pd.Series(['A0', 'A1', 'A2'])
b = pd.Series([f'B{i}' for i in range(5)])

*Example: Concatenating two Series along the row axis*

-   Use [`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)
-   Optionally specify `axis=0` (the default)
-   Might need to reset index of result object
-   Index can be reset automatically by specifying `ignore_index=True`

In [173]:
s_concat = pd.concat((a, b))
s_concat

0    A0
1    A1
2    A2
0    B0
1    B1
2    B2
3    B3
4    B4
dtype: str

In [174]:
s_concat = s_concat.reset_index(drop=True)
s_concat

0    A0
1    A1
2    A2
3    B0
4    B1
5    B2
6    B3
7    B4
dtype: str

In [175]:
pd.concat((a, b), axis = 0, ignore_index=True)

0    A0
1    A1
2    A2
3    B0
4    B1
5    B2
6    B3
7    B4
dtype: str

*Example: Concatenating along the column axis*

-   Need to specify `axis=1` argument
-   Use `keys` to specify column names

In [176]:
pd.concat((a, b), axis=1)

     0   1
0   A0  B0
1   A1  B1
2   A2  B2
3  NaN  B3
4  NaN  B4

In [177]:
# Give names to resulting columns
pd.concat((a, b), axis = 1, keys=['Column A', 'Column B'])

  Column A Column B
0       A0       B0
1       A1       B1
2       A2       B2
3      NaN       B3
4      NaN       B4

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

1. Create a new `Series` with observations `['C0', 'C1']`.
2. Using the previously created `Series` `a` and `b`, concatenate all three objects
   along the row axis and create a new (unique) index.
3. Concatenate all three objects along the column axis. Assign the column names
   `'Column1'`, `'Column2'`, and `'Column3'` using `keys`, without
   `ignore_index=True`.

</div>
<span style="display: none;">YourTurnEnd</span>

In [178]:
c = pd.Series(['C0', 'C1'])

pd.concat((a, b, c), ignore_index= True)

0    A0
1    A1
2    A2
3    B0
4    B1
5    B2
6    B3
7    B4
8    C0
9    C1
dtype: str

In [179]:
pd.concat((a, b, c), axis = 1, keys = ['Column A', 'Column B', 'Column C'])

  Column A Column B Column C
0       A0       B0       C0
1       A1       B1       C1
2       A2       B2      NaN
3      NaN       B3      NaN
4      NaN       B4      NaN

### Concatenating DataFrames

In [180]:
# Create demo DataFrames

import numpy as np
import pandas as pd

# Create 2 x 2 DataFrame of string data
df_a = pd.DataFrame(np.array([f'A{i}' for i in range(4)]).reshape((2, 2)))

# Create 2 x 3 DataFrame of string data
df_b = pd.DataFrame(np.array([f'B{i}' for i in range(6)]).reshape((2, 3)))

#### Concatenating along the column axis

*Example: Concatenating two DataFrames along the column axis*

-   Might need to reset non-unique column index (or specify `ignore_index=True`)
-   Use `keys` argument to `concat()` to add outer level to column index

In [181]:
# Resulting DataFrame as a hierarcical index
df_c = pd.concat((df_a, df_b), axis = 1, keys = ['A', 'B'])
df_c

    A       B
    0   1   0   1   2
0  A0  A1  B0  B1  B2
1  A2  A3  B3  B4  B5

In [182]:
# Want to extract column 0 in in block A
df_c[('A', 0)]

0    A0
1    A2
Name: (A, 0), dtype: str

#### Concatenating along the row axis

*Example: Concatenating rows with identical columns*

In [183]:
# .T means transpose
df_c = df_b.T

In [184]:
df_c

    0   1
0  B0  B3
1  B1  B4
2  B2  B5

In [185]:
pd.concat((df_a, df_c), axis = 0)

    0   1
0  A0  A1
1  A2  A3
0  B0  B3
1  B1  B4
2  B2  B5

*Example: Concatenating rows with different columns*

In [186]:
pd.concat((df_a, df_b), axis = 0)

    0   1    2
0  A0  A1  NaN
1  A2  A3  NaN
0  B0  B1   B2
1  B3  B4   B5

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data files located in the folder `../../data/FRED` to perform the following tasks:

1. Load the data in `FRED_monthly_1950.csv` and `FRED_monthly_1960.csv` into two different DataFrames.
   The files contain monthly macroeconomic time series for the 1950s and 1960s, respectively.
   *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically parse strings stored in the `DATE` column as dates.
2. Concatenate these DataFrames along the row dimension to get a total of 240 observations.
3. Set the column `DATE` as index for the newly created DataFrame.
</div>
<span style="display: none;">YourTurnEnd</span>

In [187]:
# Read in data used for "Your turn" exercise

# Relative path to data directory
DATA_PATH = '../../data'

# Read in FRED data for 1950s and 1960s
df_1950 = pd.read_csv(f'{DATA_PATH}/FRED/FRED_monthly_1950.csv', parse_dates=['DATE'])
df_1960 = pd.read_csv(f'{DATA_PATH}/FRED/FRED_monthly_1960.csv', parse_dates=['DATE'])

In [188]:
df_final = pd.concat((df_1950, df_1960), axis=0, ignore_index= True).set_index('DATE')
df_final

             CPI  UNRATE  FEDFUNDS  REALRATE  LFPART
DATE
1950-01-01  23.5     6.5       NaN       NaN    58.9
1950-02-01  23.6     6.4       NaN       NaN    58.9
1950-03-01  23.6     6.3       NaN       NaN    58.8
1950-04-01  23.6     5.8       NaN       NaN    59.2
1950-05-01  23.8     5.5       NaN       NaN    59.1
...          ...     ...       ...       ...     ...
1969-08-01  36.9     3.5       9.2       NaN    60.3
1969-09-01  37.1     3.7       9.2       NaN    60.3
1969-10-01  37.3     3.7       9.0       NaN    60.4
1969-11-01  37.5     3.5       8.8       NaN    60.2
1969-12-01  37.7     3.5       9.0       NaN    60.2

[240 rows x 5 columns]

***
## Merging and joining data sets

### Types of merges

We can merge DataFrames `A` and `B` in various ways:

1.  *one-to-one*: Unique keys in `A` and `B`
2.  *many-to-one*: Repeated keys in `A`, unique keys in `B`
3.  *many-to-many*: Non-unique keys in both data sets. For each matching key,
    the result contains all combinations of the corresponding rows from both
    data sets. This should usually be avoided.

### Implementation in pandas

1.  [`pd.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html):
    function that takes as argument the *two* DataFrames to be merged,
    e.g.,
    
    ```python
    result = pd.merge(df_A, df_B)
    ```
2.  [`df.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html):
    method of a specific `DataFrame` object, takes the other `DataFrame` as argument, e.g.,
    
    ```python
    result = df_A.merge(df_B)
    ```

### Controlling the resulting data set

Merge methods (controlled by `how` argument to `merge()`):

1.  `how='inner'` (_inner join_): _intersection_ of keys that are present in _both_ data sets
2.  `how='outer'` (_outer join_): _union_ of keys present in either of the data sets
3.  `how='left'` (_left join_): all identifiers from the _left_ data set are in the result
4.  `how='right'` (_right join_): all identifiers from the _right_ data set are in the result

Illustration: Each circle represents the keys present in the left (`df1`) or right (`df2`) DataFrames. The merge method controls which subset of keys is retained in the merge result.

![Join types](join-methods.png)

***
### Merging with `pd.merge()`

#### One-to-one merges

In [189]:
# Create first DataFrame with 2 rows
df_a = pd.DataFrame({'key': [0, 1], 'value_a': ['A0', 'A1']})

# Create second DataFrame with 2 rows
df_b = pd.DataFrame({'key': [1, 2], 'value_b': ['B1', 'B2']})

In [190]:
df_a

   key value_a
0    0      A0
1    1      A1

In [191]:
df_b

   key value_b
0    1      B1
1    2      B2

*Example: inner join*

-   By default, `pd.merge()` performs inner join on all overlapping columns
-   Argument `on` controls on which columns to match (default: use all overlapping columns)
-   Argument `how` controls which rows to keep in result

In [192]:
# Default: perform inner join
df_merged = pd.merge(df_a, df_b)
df_merged

# You want to write explicitly:
pd.merge(df_a, df_b, on='key', how='inner')

   key value_a value_b
0    1      A1      B1

In [193]:
# perform outer merge
pd.merge(df_a, df_b, on= 'key', how= 'outer')

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1
2    2     NaN      B2

In [194]:
pd.merge(df_a, df_b, on='key', how='left')

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1

*Example: outer, left, and right join*

-   Specify `how='outer'`, `how='left'`, `how='right'`

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data files located in the folder `../../data/FRED` to perform the following
tasks:

1. Load the data in `CPI.csv` and `GDP.csv` into two different DataFrames.
   The files contain monthly data for the Consumer Price Index (CPI) and quarterly data
   for GDP, respectively.
   *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically parse strings
   stored in the `DATE` column as dates.
2. Merge the CPI and the GDP time series with
   [`pd.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html)
   without specifying the `how=` argument.
3. Merge the CPI and the GDP time series with `pd.merge()`
   using a left join (`how='left'`).
4. Repeat the merge using an inner join (`how='inner'`). Confirm that the
   result matches step 2.

How do the results differ depending on the value of the `how` argument?

</div>
<span style="display: none;">YourTurnEnd</span>

In [195]:
# Data used for "Your turn" exercise
df_cpi = pd.read_csv(f'{DATA_PATH}/FRED/CPI.csv', parse_dates=['DATE'])
df_gdp = pd.read_csv(f'{DATA_PATH}/FRED/GDP.csv', parse_dates=['DATE'])

In [196]:
df_cg = pd.merge(df_cpi, df_gdp, on='DATE')
df_cg

          DATE    CPI      GDP
0   1947-01-01   21.5   2182.7
1   1947-04-01   22.0   2176.9
2   1947-07-01   22.2   2172.4
3   1947-10-01   22.9   2206.5
4   1948-01-01   23.7   2239.7
..         ...    ...      ...
313 2025-04-01  320.3  23771.0
314 2025-07-01  322.2  24026.8
315 2025-10-01    NaN  24055.7
316 2026-01-01  326.6  24180.4
317 2026-04-01  332.4  24270.6

[318 rows x 3 columns]

In [197]:
df_cg = pd.merge(df_cpi, df_gdp, on='DATE', how = 'left')
df_cg

          DATE    CPI      GDP
0   1947-01-01   21.5   2182.7
1   1947-02-01   21.6      NaN
2   1947-03-01   22.0      NaN
3   1947-04-01   22.0   2176.9
4   1947-05-01   22.0      NaN
..         ...    ...      ...
949 2026-02-01  327.5      NaN
950 2026-03-01  330.3      NaN
951 2026-04-01  332.4  24270.6
952 2026-05-01  334.0      NaN
953 2026-06-01  332.6      NaN

[954 rows x 3 columns]

In [198]:
df_cg = pd.merge(df_cpi, df_gdp, on='DATE', how = 'inner')
df_cg

          DATE    CPI      GDP
0   1947-01-01   21.5   2182.7
1   1947-04-01   22.0   2176.9
2   1947-07-01   22.2   2172.4
3   1947-10-01   22.9   2206.5
4   1948-01-01   23.7   2239.7
..         ...    ...      ...
313 2025-04-01  320.3  23771.0
314 2025-07-01  322.2  24026.8
315 2025-10-01    NaN  24055.7
316 2026-01-01  326.6  24180.4
317 2026-04-01  332.4  24270.6

[318 rows x 3 columns]

#### Many-to-one merges

*Example: merge unique values in `df_b` to multiple values in `df_a`*

In [199]:
# Create first DataFrame with 4 rows, non-unique key
df_a = pd.DataFrame({'key': [0, 1, 0, 1], 'value_a': ['A0', 'A1', 'A2', 'A3']})

# Create second DataFrame with 2 rows, unique key
df_b = pd.DataFrame({'key': [0, 1], 'value_b': ['B0', 'B1']})

In [200]:
df_a

   key value_a
0    0      A0
1    1      A1
2    0      A2
3    1      A3

In [201]:
df_b

   key value_b
0    0      B0
1    1      B1

In [202]:
pd.merge(df_a, df_b)

   key value_a value_b
0    0      A0      B0
1    1      A1      B1
2    0      A2      B0
3    1      A3      B1

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

1. Load `../../data/titanic.csv` into a DataFrame named `titanic`.
2. Create a small lookup DataFrame `ports` mapping port codes to full names:
   ```python
   ports = pd.DataFrame({
       'Embarked': ['C', 'Q', 'S'],
       'PortName': ['Cherbourg', 'Queenstown', 'Southampton'],
   })
   ```
3. Merge `titanic` and `ports` on `Embarked` using the
   [`pd.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html)
   function with `how='left'` to retain all passengers.
4. Inspect the first few rows of the merged DataFrame. Notice how each full
   port name is matched to multiple passenger rows, as this is a many-to-one
   merge.

</div>
<span style="display: none;">YourTurnEnd</span>

In [220]:
# Data used for "Your turn" exercise
titanic = pd.read_csv(f'{DATA_PATH}/titanic.csv')

ports = pd.DataFrame(
    {
        'Embarked': ['C', 'Q', 'S'],
        'PortName': ['Cherbourg', 'Queenstown', 'Southampton'],
    }
)

In [221]:
titanic['Embarked'].value_counts(dropna = False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [224]:
df_merged = pd.merge(titanic, ports, on = 'Embarked', how = 'left')
df_merged

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,PortName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,Cherbourg
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,Southampton
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,Southampton
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S,Southampton
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,Queenstown

In [225]:
df_merged['PortName'].value_counts()

PortName
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

***
### Merging with `DataFrame.merge()`

-   Equivalent to `pd.merge()`

*Example: repeat one-to-one merges from above*

In [204]:
# Create first DataFrame with 2 rows
df_a = pd.DataFrame({'key': [0, 1], 'value_a': ['A0', 'A1']})

# Create second DataFrame with 2 rows
df_b = pd.DataFrame({'key': [1, 2], 'value_b': ['B1', 'B2']})

In [ ]:
#
df_a.merge(df_b)

   key value_a value_b
0    1      A1      B1

*Example: Merging with overlapping column names*

In [229]:
# Rename columns to common name 'value'
df_a = df_a.rename(columns={'value_a': 'value'})
df_b = df_b.rename(columns={'value_b': 'value'})

In [233]:
df_a.merge(df_b, on = 'key', how='inner', suffixes = ('_left', '_right'))

   key value_left value_right
0    1         A1          B1

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data files located in the folder `../../data/FRED` to compare inflation
and the Federal Reserve policy interest rate:

1. Load `INFLATION.csv` and `FEDFUNDS.csv` into two DataFrames, parsing strings
   in the `DATE` column as dates.
2. Rename the data column in each DataFrame to `'rate'` using the
[`rename()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)
   method.
3. Merge the two DataFrames using the
[`merge()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)
   method without specifying `on`. Notice that it returns only a few rows where
   the inflation rate happened to equal the policy rate.
4. Merge the DataFrames on `DATE` using `suffixes=('_inflation', '_fedfunds')`.
5. Compare an inner join with a left join (`how='left'`). Why does the left
   join retain more observations?

</div>
<span style="display: none;">YourTurnEnd</span>

In [234]:
# Data used for "Your turn" exercise
df_infl = pd.read_csv(f'{DATA_PATH}/FRED/INFLATION.csv', parse_dates=['DATE'])
df_ff = pd.read_csv(f'{DATA_PATH}/FRED/FEDFUNDS.csv', parse_dates=['DATE'])

***
### Merging with `join()`

The `DataFrame` method 
[`join()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html) 
is a convenience wrapper around 
[`pd.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html):

1.  `join()` can be called _only_ directly on the `DataFrame` object
2.  `join()` always operates on the _index_ of the other `DataFrame`
3.  `join()` by default performs a `left` join, whereas `merge()` performs an `inner` join

Use `join()` if you want to join DataFrames which have a similar index.

*Example: joining DataFrames*

In [207]:
# Create first DataFrame with 2 rows
df_a = pd.DataFrame(['A0', 'A1'], columns=['value_a'], index=[0, 1])

# Create second DataFrame with 2 rows
df_b = pd.DataFrame(['B1', 'B2'], columns=['value_b'], index=[1, 2])

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data files located in the folder `../../data/FRED` to perform the following tasks:

1. Load the data in `CPI.csv` and `GDP.csv` into two different DataFrames.
   The files contain monthly data for the Consumer Price Index (CPI) and quarterly data for GDP, respectively.
   *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically parse strings stored in the `DATE` column as dates.
2. Set the `DATE` column as the index for each of the two DataFrames.
3. Merge the CPI with the GDP time series with
   [`join()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html).
   Do this with both a left and an inner join.
</div>
<span style="display: none;">YourTurnEnd</span>

In [208]:
# Data used for "Your turn" exercise
df_cpi = pd.read_csv(f'{DATA_PATH}/FRED/CPI.csv', parse_dates=['DATE'])
df_gdp = pd.read_csv(f'{DATA_PATH}/FRED/GDP.csv', parse_dates=['DATE'])

***
## Dealing with missing values

-   Often created as result of `pd.merge()` or `pd.concat()` if operands don't have the same row or column index

In [235]:
# Create two DataFrames with partially overlapping keys
df_a = pd.DataFrame({'key': [0, 1], 'value_a': ['A0', 'A1']})
df_b = pd.DataFrame({'key': [1, 2], 'value_b': ['B1', 'B2']})

# Merge with outer join, thus creating missing values
df_merged = pd.merge(df_a, df_b, on='key', how='outer')
df_merged

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1
2    2     NaN      B2

### Dropping missing values

Missing values can be dropped by either

1.  Using 
    [`dropna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)
2.  Selecting a subset of observations with a boolean operation such as 
    [`notna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.notna.html) 
    or 
    [`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html).
3. Avoiding the missing values in the first place, e.g., by using
   `merge(..., how='inner')`, unless these are already present in the original
   DataFrames.

*Example: Dropping missing values*

- Use _outer/left/right join_ and drop missing data with 
  [`dropna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

In [236]:
# Drops all rows where any column has missing values
df_merged.dropna()

   key value_a value_b
1    1      A1      B1

In [237]:
# Drop only subset
df_merged.dropna(subset=['value_a'])

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Instead of using `dropna()`, drop the missing observations using either 
[`notna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.notna.html)
or
[`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html).

1. Drop all rows with any missing observations.

    *Hint:* You can apply `notna()` or `isna()` to all columns at once and combine
    the results with
    [`any()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html)
    or
    [`all()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html).
    
2. Drop all rows with missing observations in column `value_a`.

</div>
<span style="display: none;">YourTurnEnd</span>

In [210]:
# Data used for "Your turn" exercise
df = pd.merge(df_a, df_b, on='key', how='outer')

*Example: Avoiding missing values in the first place*

- E.g., use _inner join_ when merging data sets
- Missing values already present in the original DataFrames can remain

### Filling missing values

Instead of dropping data, we can impute missing values in various ways:

1.  [`fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html): 
    replace missing data with user-specified values
2.  [`ffill()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ffill.html) 
    and 
    [`bfill()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bfill.html): 
    fill missing values
    forward or backward from adjacent non-missing observations
3.  [`interpolate()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html): 
    interpolate missing values based on non-missing ones

*Example: Replacing missing values with `fillna()`*

- Specify one value for _entire_ `DataFrame`
- Specify different value for each column using a dictionary

In [240]:
df_merged.fillna(1)

   key value_a value_b
0    0      A0       1
1    1      A1      B1
2    2       1      B2

In [241]:
df_merged.fillna({'value_a': 'Default A', 'value_b' : 'Default B'})

   key    value_a    value_b
0    0         A0  Default B
1    1         A1         B1
2    2  Default A         B2

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use `../../data/titanic.csv` to practice column-specific imputation:

1. Load `titanic.csv` into a DataFrame named `titanic`.
2. Use the
[`fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)
   method with a dictionary to replace missing values in `Cabin` with
   `'Unknown'`, and missing values in `Age` with the sample average of `Age`.
3. Verify that neither column contains missing values in the updated DataFrame
   using
[`notna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.notna.html)
   combined with
[`all()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html)
   (e.g., `titanic[['Cabin', 'Age']].notna().all()`).

</div>
<span style="display: none;">YourTurnEnd</span>

In [252]:
# Data used for "Your turn" exercise
titanic = pd.read_csv(f'{DATA_PATH}/titanic.csv')
print(titanic['Age'].mean())
titanic_filled = titanic.fillna({'Cabin': 'Unknown', 'Age' : titanic['Age'].mean()})

29.69911764705882

In [253]:
titanic_filled[['Cabin', 'Age']].notna().all()

Cabin    True
Age      True
dtype: bool

In [255]:
titanic_filled.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   Ticket       891 non-null    str
 7   Fare         891 non-null    float64
 8   Cabin        891 non-null    str
 9   Embarked     889 non-null    str
dtypes: float64(2), int64(3), str(5)
memory usage: 69.8 KB

*Example: forward- or backward-filling missing values*

- Use 
  [`ffill()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ffill.html) 
  to forward-fill
- Use 
  [`bfill()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bfill.html) 
  to backward-fill

In [256]:
df_merged

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1
2    2     NaN      B2

In [257]:
#Fill in missing obs. from previous obs
df_merged.ffill()

   key value_a value_b
0    0      A0     NaN
1    1      A1      B1
2    2      A1      B2

In [258]:
# Fill missing from next non missinng obs
df_merged.bfill()

   key value_a value_b
0    0      A0      B1
1    1      A1      B1
2    2     NaN      B2

*Example: linear interpolation*

- Use 
  [`interpolate()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.interpolate.html) 
  to interpolate missing _numerical_ data (e.g., `method='linear'`)

In [212]:
s = pd.Series([1.0, 2.0, 3.0, np.nan, 5.0])

In [260]:
s.interpolate(method = 'linear')

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data files located in the folder `../../data/FRED` to perform the following
tasks:

1. Load the data in `CPI.csv` and `GDP.csv` into two different DataFrames.
   The files contain monthly data for the Consumer Price Index (CPI) and quarterly data
   for GDP, respectively.
   *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically parse strings
   stored in the `DATE` column as dates.
2. Merge the CPI with the GDP time series with `merge()` using a left join. This creates
   missing values in the `GDP`
   column.
3. Impute the missing GDP values using 
   [`interpolate()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.interpolate.html) 
   and replace the missing values in column `GDP`.
   Note that the default method fills trailing missing values with the last
   observed value. Use `limit_area='inside'` to fill only gaps between observations.

</div>
<span style="display: none;">YourTurnEnd</span>

In [213]:
# Data used for "Your turn" exercise
df_cpi = pd.read_csv(f'{DATA_PATH}/FRED/CPI.csv', parse_dates=['DATE'])
df_gdp = pd.read_csv(f'{DATA_PATH}/FRED/GDP.csv', parse_dates=['DATE'])